export const ROUTES = {
  login: '/login',
  register: '/register',
  dashboard: '/dashboard',
  sources: '/sources',
  addSource: '/sources/add',
  widgets: '/widgets',
  roles: '/roles',
  roleCreate: '/roles/create',
  users: '/users',
  dashboards: '/dashboards',
  dashboardDetail: '/dashboards/:id',
  editWidget: '/widgets/edit/:id',
  createWidget: '/widgets/create',
  dashboardList: '/dashboards',
  createDashboard: '/dashboards/create',
  createRole: '/roles/create',
  dashboardShare: '/dashboard/share/:shareId',

};
